name: UFO 
channels:
  - defaults
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - xarray
  - pandas
  - cartopy
  - cython
  - jupyter
  - jupyterlab
  - pyyaml
  - autopep8
  - scikit-learn
